# Generated by Django 4.1.5 on 2023-01-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
                ('todays_wc', models.IntegerField()),
                ('date', models.DateField(verbose_name="today's date")),
            ],
        ),
    ]
