# Generated by Django 4.1.5 on 2023-01-26 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywc',
            name='text_area',
            field=models.CharField(blank=True, default='', max_length=500000),
        ),
        migrations.AlterField(
            model_name='dailywc',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name="today's date"),
        ),
        migrations.AlterField(
            model_name='dailywc',
            name='project_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
