# Generated by Django 4.1.5 on 2023-02-03 21:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unassigned', max_length=255)),
                ('start_date', models.DateField(default=datetime.date.today, verbose_name="today's date")),
                ('end_date', models.DateField()),
                ('word_count_goal', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='dailywc',
            name='project_name',
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='end date'),
        ),
        migrations.AddField(
            model_name='dailywc',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='writingapp.project'),
        )
    ]
