# Generated by Django 4.1.5 on 2023-02-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywc',
            name='daily_goal',
            field=models.IntegerField(default=0),
        ),
    ]
