# Generated by Django 4.1.5 on 2023-02-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0002_remove_dailywc_project_name_alter_project_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.CharField(default='2023-02-06', max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.CharField(default='2023-02-06', max_length=255),
        ),
    ]
