# Generated by Django 4.1.5 on 2023-01-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writingapp', '0002_dailywc_text_area_alter_dailywc_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailywc',
            name='text_area',
            field=models.CharField(blank=True, default='Text here.', max_length=500000),
        ),
    ]
