# Generated by Django 4.1.5 on 2023-02-01 18:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('writingapp', '0004_dailywc_accessed_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailywc',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
